"""Public data models used by the QR generation pipeline."""

from dataclasses import dataclass
from typing import Literal, TypeAlias


ErrorLevel = Literal["L", "M", "Q", "H"]
QRMode = Literal["numeric", "alphanumeric", "byte", "kanji", "hanzi"]
SizeMode = Literal["fixed_size", "fixed_module"]
LogoShape = Literal["circle", "square", "rounded_square"]
OutputFormat = Literal["png", "svg", "jpg", "jpeg"]
RGBA: TypeAlias = tuple[int, int, int, int]
Matrix: TypeAlias = tuple[tuple[bool, ...], ...]


@dataclass(frozen=True, slots=True)
class QRCoreRequest:
    """Values which affect QR encoding rather than presentation."""

    text: str
    error_level: ErrorLevel
    encoding: str = "utf-8"
    use_eci: bool = True
    quiet_zone_modules: int = 4
    version: int | None = None


@dataclass(frozen=True, slots=True)
class QRAnalysis:
    """Encoding result, including the body matrix without a quiet zone."""

    text: str
    encoding: str
    use_eci: bool
    requested_error_level: str
    actual_error_level: str
    version: int
    designator: str
    mode: str | None
    mask: int
    char_count: int
    encoded_byte_count: int
    matrix_size: int
    quiet_zone_modules: int
    total_modules: int
    dark_module_count: int
    light_module_count: int
    matrix: Matrix


@dataclass(frozen=True, slots=True)
class LogoRequest:
    """Logo source and its QR-local pixel geometry."""

    enabled: bool = False
    file_path: str | None = None
    width: int | None = None
    height: int | None = None
    shape: LogoShape = "square"
    corner_radius: int = 0
    padding: int = 0
    x: int | None = None
    y: int | None = None
    canvas_width: int | None = None
    canvas_height: int | None = None
    transparent_background: bool = True
    background_color: RGBA = (255, 255, 255, 255)


@dataclass(frozen=True, slots=True)
class QRRequest:
    """Complete request consumed by :func:`qr_backend.generate_qr`."""

    core: QRCoreRequest
    size_mode: SizeMode
    qr_width: int | None = None
    qr_height: int | None = None
    pixels_per_module: int | None = None
    canvas_width: int | None = None
    canvas_height: int | None = None
    qr_position_x: int | None = None
    qr_position_y: int | None = None
    foreground_color: RGBA = (0, 0, 0, 255)
    background_color: RGBA = (255, 255, 255, 0)
    canvas_color: RGBA = (255, 255, 255, 255)
    logo: LogoRequest | None = None
    output_format: OutputFormat = "png"
    dpi: int | None = None


@dataclass(frozen=True, slots=True)
class QRLayout:
    """Solved dimensions in QR-pixel and final-canvas spaces."""

    size_mode: SizeMode
    qr_width: int
    qr_height: int
    canvas_width: int
    canvas_height: int
    qr_x: int
    qr_y: int
    module_width: float
    module_height: float
    pixels_per_module: int | None


@dataclass(frozen=True, slots=True)
class LogoLayout:
    """Logo and cutout rectangles in QR-local pixel coordinates."""

    logo_x: int
    logo_y: int
    logo_width: int
    logo_height: int
    cutout_x: int
    cutout_y: int
    cutout_width: int
    cutout_height: int
    shape: LogoShape
    corner_radius: int


@dataclass(frozen=True, slots=True)
class LogoSafetyResult:
    """Protected body modules touched by the actual cutout shape."""

    safe: bool
    protected_module_count: int
    overlapping_modules: tuple[tuple[int, int], ...]


@dataclass(frozen=True, slots=True)
class QRResult:
    """Generated bytes plus metadata useful to an API adapter."""

    image_bytes: bytes
    output_format: str
    version: int
    error_level: str
    matrix_size: int
    total_modules: int
    qr_width: int
    qr_height: int
    canvas_width: int
    canvas_height: int
    qr_x: int
    qr_y: int
    size_mode: str
    pixels_per_module: int | None
    logo_used: bool
    dpi: int | None
